modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="nbt_ac"
version="1.0"
displayName="NBT Autocomplete"
logoFile="logo.png"
authors="mt1006 (mt1006x)"
description="Adds suggestions for NBT tags"

[[dependencies.nbt_ac]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nbt_ac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
