modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="nbt_ac"
version="1.1"
displayName="NBT Autocomplete"
logoFile="logo.png"
authors="mt1006 (mt1006x)"
description="Adds suggestions for NBT tags"

[[dependencies.nbt_ac]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nbt_ac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
