modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mixins.${mod_id}.json"

[[dependencies.${mod_id}]]
	modId="neoforge"
	required=true
	versionRange="${neoforge_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="minecraft"
	required=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"